name: hChat
version: '${version}'
main: fr.ht06.hchat.HChat
api-version: '1.20'
author: ht06
softdepend: [PlaceholderAPI] # This is used, if your plugin works without PlaceholderAPI.
commands:
  hChat:
    description: the credit of the plugin.

  colorcode:
    description: display the colorcode of Minecraft.

  hChatreload:
    description: reload config.yml of the plugin
    aliases:
      - hcreload
      - hcrl

  mute:
    description: Mute the player
