#This plugin require PlaceholderAPI, you can download it Here : https://www.spigotmc.org/resources/placeholderapi.6245/
#Exemple with luckperm :
#Player_Info: "%luckperms_prefix% %player_name% %luckperms_suffix%: "
Player_Info: "%player_name%: "

#You can set a permission to use the Chat in color or have the default one
ColorChat-Permission: "hChat.colorchat"