name: hChat
main: fr.ht06.hChat.Main
version: 1.5
author: ht06
description: A plugin that allow you to change the prefix of any player, use API (like PlaceholderAPI) and more things...
load: POSTWORLD
depend:
  - PlaceholderAPI
commands:
  hChat:
    description: the credit of the plugin.

  colorcode:
    description: display the colorcode of Minecraft.

  hChatreload:
    description: reload config.yml of the plugin
    aliases:
      - hcreload
      - hcrl
