name: hChat
main: fr.ht06.hChat.Main
version: 1.0
author: ht06
description: A plugin that allow you to change the prefix of any player, use API (like PlaceholderAPI) and more things...
depend:
  - PlaceholderAPI
